- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/templates/_helpers.tpl
- charts/gitops-runtime/values.yaml
> referencing dev helm chart of gitops-operator

- charts/gitops-runtime/Chart.yaml
> fixed lint

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> CR-22296-app-proxy

- charts/gitops-runtime/Chart.yaml
> CR-vuln-revert

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> release 0.4.5 fix cmp plugin

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> bump app-proxy to 1.2667.0

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> application versions

- charts/gitops-runtime/README.md
> App versions

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
> Release 0.4.6

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
> bump app-proxy

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
Revert changin app-proxy version
Most likely contains regression with ISC
> Revert app proxy 

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
> update app-proxy image to 1.2696.0

- charts/gitops-runtime/Chart.yaml
> update argo-cd to 5.53.12-8-cap-2.9-2024.3.14-6cca9ccf8

- charts/gitops-runtime/Chart.yaml
> chore: update argocd to 5.53.12-9-cap-2.9-2024.3.17-6fd9979e1 

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
> Release 0.5.1

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
update gitops-operator subchart
contains promotion-template manifest and code
> support promotions

- .gitignore
- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/templates/_components/cap-app-proxy/_pdb.yaml
- charts/gitops-runtime/templates/_components/internal-router/_pdb.yaml
- charts/gitops-runtime/templates/app-proxy/pdb.yaml
- charts/gitops-runtime/templates/internal-router/pdb.yaml
- charts/gitops-runtime/values.yaml
Add PDBs to internal-router and app-proxy
> feat: add PDBs

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> update argo-cd to 5.53.12-10-cap-v2.9-2024.4.10-dcc1723fd

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
Upgrade argo-cd to v2.9-2024.4.10-dcc1723fd which includes fix for application versions
> Release 0.5.3

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
> feat: update app-proxy image 1.2751.1

- CODEOWNERS
> feat: extended CODEOWNERS with team leads and Pasha

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/templates/codefresh-cm.yaml
- charts/gitops-runtime/values.yaml
> feat: codefresh-gitops-operator with product crd updates

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
> fix: sealed secret shearing among clusters

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/templates/codefresh-cm.yaml
- charts/gitops-runtime/values.yaml
* product CRD (latest)
* gitops operator
* app-proxy
> release 0.6.1

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> Release 0.7.0 - Add Redis authentication to ArgoCD

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/templates/_helpers.tpl
> Fix-release-0.7.1

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/ci/values-all-images.yaml
- charts/gitops-runtime/tests/values/mandatory-values-ingress.yaml
- charts/gitops-runtime/tests/values/mandatory-values-no-token.yaml
- charts/gitops-runtime/tests/values/mandatory-values.yaml
- charts/gitops-runtime/values.yaml
> Feat: Add garage for workflow logging as optional dependency

- charts/gitops-runtime/Chart.yaml
fix garage subchart condition
condition field in Chart.yaml does not work with complex boolean logic
> fix garage subchart condition

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> feat: app-proxy with new query promotablePropertiesPreview

- charts/gitops-runtime/Chart.yaml
> feat: upgrade codefresh-gitops-operator to 1.0.24

- charts/gitops-runtime/Chart.yaml
> feat: argo-cd 2.11

- charts/gitops-runtime/README.md
> release 0.8.0 docs fix

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> Release 0.8.0

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> fix: argo-cd with fix for app metadata change event reporting

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> Release 0.8.1

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> fix: gitops operator with security fixes

- .gitignore
- charts/gitops-runtime/templates/_components/internal-router/_configmap.yaml
- charts/gitops-runtime/values.yaml
> fix - disable ipv6 by default in internal router

- charts/gitops-runtime/Chart.yaml
> fix - ArgoCD event reporter servicemonitor selector lables (#241)

- charts/gitops-runtime/Chart.yaml
> Patch - security ArgoCD webhook processing

- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
update app-proxy to 1.2946.0
contains fix for host-mapping
> feat: update app-proxy to `1.2946.0`

- charts/gitops-runtime/Chart.yaml
>  Feat: update argo-events chart to 2.4.7-1-cap-CR-24607 

- charts/gitops-runtime/values.yaml
update app-proxy to `1.2963.0`
removed CLI and HOSTED code from app-proxy
> feat(app-proxy): update app-proxy to `1.2963.0`

- charts/gitops-runtime/values.yaml
> update init container version

- charts/gitops-runtime/Chart.yaml
> fix - support non default ArgoCD server host in event reporter

- charts/gitops-runtime/Chart.yaml
upgrade operator to 0.2.10
additional product release termination task
> feat: upgrade gitops operator

- charts/gitops-runtime/values.yaml
> fix: bump app-proxy to 1.2989.3 - fix configurationRuntime not working immediately after installation

- charts/gitops-runtime/templates/_components/cap-app-proxy/environment-variables/_main-container.yaml
the env var should be set on app-proxy
> added IS_CONFIGURATION_RUNTIME env var

- charts/gitops-runtime/Chart.yaml
This pull request fixes an issue in the action script where the response was not being parsed correctly using jq.
> fix: action script fails to extract commit_sha from response

- charts/gitops-runtime/Chart.yaml
> fix: use prod quay instead of dev

- charts/gitops-runtime/values.yaml
update app-proxy to `1.3056.1` - search repos by url
improve on current behavior, which was searching by name only
> feat: update app-proxy to `1.3056.1` - search repos by url

- charts/gitops-runtime/README.md
> chore: add breaking change notice to the README.md

- charts/gitops-runtime/Chart.yaml
re-created pr with branch name in lowercase to pass e2e
> feat: argo-cd with event-reporter update to report change revisions metadata in app annotations

- charts/gitops-runtime/values.yaml
> feat: bump app-proxy to `1.3094.0` - changeRevision fields support

- README.md
- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
https://codefresh-io.atlassian.net/browse/CR-25575
https://codefresh-io.atlassian.net/browse/CR-25570
https://codefresh-io.atlassian.net/browse/CR-25571
> chore: update kube-rbac-proxy, sealed-secrets-controller and argo-events nats to latest

- charts/gitops-runtime/values.yaml
> feat: app-proxy with new rollout steps support setHeaderRoute and setMirrorRoute

- charts/gitops-runtime/values.yaml
> feat: bump app-proxy to `1.3138.0` with promote all functionality

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> chore(cr-25581): updating app proxy, (fixed vulnerabilities in expat, curl, openssl)

- charts/gitops-runtime/values.yaml
> feat: bump app-proxy to `1.3142.0` with refresh in-cluster app after any related commit

- charts/gitops-runtime/values.yaml
> fix: bump cap-app-proxy to 1.3146.0 - fix: accessing repo in parallel

- charts/gitops-runtime/Chart.yaml
> chore(): updated frpc with security fixes

- charts/gitops-runtime/Chart.yaml
> fix: argo-cd with repo-server repeated resources fix

- charts/gitops-runtime/Chart.yaml
fail submit-tmpl step if child wf failed
> chore: update codefresh-gitops-operator to 0.3.12

- charts/gitops-runtime/Chart.yaml
> feat: argo-cd with multi-source app info reporting 

- charts/gitops-runtime/templates/_components/cap-app-proxy/_config.yaml
> fix: add isConfigurationRuntime value to app-proxy cm

- charts/gitops-runtime/templates/_components/cap-app-proxy/_config.yaml
> fix placement of isConfigurationRuntime field

- charts/gitops-runtime/values.yaml
> update app-proxy to 1.3192.0

- charts/gitops-runtime/values.yaml
fixed case when release would fail when a step has no changes
> updated app-proxy to 1.3196.4 - throw original exception in case of NO_CHANGES

- charts/gitops-runtime/Chart.yaml
> fix: upgrade argo events to fix security vulnerability

- charts/gitops-runtime/Chart.yaml
> feat: update to upstream argo-cd 2.13.3 and helm 7.7.14 

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
New optional dependency cf-argocd-extras
New service in the runtime
> feat: sources-server

- charts/gitops-runtime/Chart.yaml
> chore(): updated codefresh-gitops-operator

- charts/gitops-runtime/values.yaml
> feat: app-proxy  bump 1.3228.0

- installer-image/Dockerfile
> chore(CR-26970): updated cf-cliv2, kubectl

- charts/gitops-runtime/Chart.yaml
> chore: CR-26261 - updated gitops operator to v0.3.22 to support promotion queue

- charts/gitops-runtime/values.yaml
> chore(): updating csdp

- charts/gitops-runtime/values.yaml
* updating csdp
(cherry picked from commit 1dff850d38099941668eed3fc1b10294dccfbefa)
> chore(CR-26068): updating csdp

- charts/gitops-runtime/values.yaml
Adding `gitSourceConfigured` heartbeat status and firing heartbeat each time when user facing statuses change detected.
> feat: update app-proxy version (gitSourceConfigured status)

- charts/gitops-runtime/Chart.yaml
> bump gitops operator with injected param hooks support 

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> chore: updated sealed-secrets-controller

- charts/gitops-runtime/values.yaml
> chore: source server update to 2025.01.27-6069b19

- charts/gitops-runtime/Chart.yaml
> chore: updated tunnel-client(frpc)

- charts/gitops-runtime/values.yaml
> chore: updated app-proxy

- charts/gitops-runtime/Chart.yaml
- feat: upgraded git-lfs to 3.6.1 https://github.com/codefresh-io/argo-cd/pull/386
> upgraded argo-cd argo-helm to 7.7.14-5-cap-2.13.3-2025.3.5-50344f005

- charts/gitops-runtime/README.md
- charts/gitops-runtime/templates/tls-custom-ca/workflow-pipelines-git-webhooks.yaml
- charts/gitops-runtime/values.yaml
> chore: Typo in the parameter name in values file in gitops-runtime chart

- charts/gitops-runtime/values.yaml
> Updated app-proxy

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/templates/event-reporter.yaml
> fix - support byoa with ArgoCD operator

- charts/gitops-runtime/values.yaml
> feat: app-proxy update to 1.3359.0 with git manifest request revision metadata

- charts/gitops-runtime/templates/NOTES.txt
> chore: update chart NOTES.txt

- charts/gitops-runtime/Chart.yaml
> fix: argo-events 2.4.7-1-cap-CR-28072 with fix for eventsource restarts

- charts/gitops-runtime/values.yaml
> patch - fix gitops operator values

- charts/gitops-runtime/Chart.yaml
> feat: sources-server 0.3.15 with rollout rollback query

- charts/gitops-runtime/values.yaml
fix: Proxy config set in env values is not reaching container env
> feat: update app-proxy image tags to 1.3430.2

- .gitignore
- charts/gitops-runtime/Chart.yaml
> feat: update argo-cd dependency version to 7.8.23-1-cap-v2.14.9

- charts/gitops-runtime/Chart.yaml
> feat: cf-argocd-extras (0.3.16) - event-reporter with git-source data

- charts/gitops-runtime/Chart.yaml
> eat: cf-argocd-extras (0.3.17) - events with change revision data

- charts/gitops-runtime/values.yaml
> feat: app-proxy 1.3451.0 with app resource tree with annotations & labels in response

- charts/gitops-runtime/values.yaml
> updated nginx

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> updated csdp, gitops-operator with security fixes

- charts/gitops-runtime/Chart.yaml
> feat: cf-argocd-extras v0.3.22 with payloadVersion reported

- charts/gitops-runtime/values.yaml
> feat(app-proxy) - create default-git-source in new runtimes

- charts/gitops-runtime/Chart.yaml
> feat: cf-argocd-extras 0.4.0 with health status enrichment to support argo cd 3.0

- charts/gitops-runtime/values.yaml
> feat: update app-proxy to 1.3498.0 - improved error messages if they contain cause

- charts/gitops-runtime/values.yaml
> feat(app-proxy): update image tags to 1.3514.0 - fix PromotionFlow saving location in shared-config repo

- charts/gitops-runtime/Chart.yaml
Argo Helm PRs:
https://github.com/codefresh-io/argo-helm/pull/151
Upgraded Redis to 7.4.3
https://github.com/codefresh-io/argo-helm/pull/145
Argo CD PRs:
https://github.com/codefresh-io/argo-cd/pull/396
https://github.com/codefresh-io/argo-cd/pull/395
https://github.com/codefresh-io/argo-cd/pull/393
> feat: updated argo cd helm to 7.8.23-5-cap-v2.14.9-2025-05-20-9356e64a

- charts/gitops-runtime/Chart.yaml
> fix(event-reporter): service missing component label

- charts/gitops-runtime/Chart.yaml
https://github.com/codefresh-io/argo-helm/pull/173
https://github.com/codefresh-io/argo-cd/pull/398
> feat: bumped Argo CD to 7.8.23-7-cap-v2.14.9-2025-05-29-397c4f0d

- charts/gitops-runtime/Chart.yaml
* feat: update argo workflow to 0.45.15-v3.6.7-cap-CR-28355
> feat: update argo workflow to 0.45.15-v3.6.7-cap-CR-28355 (#517)

- charts/gitops-runtime/values.yaml
> feat: app-proxy 1.3546.0 with git source creation/deletion improvements in event-reporting

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> feat: bumped gitops-operator and app-proxy versions to make github enterprise promotions work

- charts/gitops-runtime/Chart.yaml
https://github.com/codefresh-io/codefresh-gitops-operator/pull/195
> fix: bump gitops operator chart to fix promotion retries

- charts/gitops-runtime/README.md
- charts/gitops-runtime/README.md.gotmpl
> fix: Argo-workflows artifact and log storage

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> chore(CR-29160): security upd nats exporter

- charts/gitops-runtime/Chart.yaml
https://github.com/codefresh-io/argo-helm/pull/179
https://github.com/codefresh-io/argo-helm/pull/178
> Feat/add GitHub api metrics and update ubuntu base image

- charts/gitops-runtime/values.yaml
> chore: app-proxy 1.3624.0 with runResourceAction adoption for 3.1+ argocd

- charts/gitops-runtime/Chart.yaml
> fix: bump cf-argocd-extras to 0.5.7

- charts/gitops-runtime/values.yaml
> chore: app-proxy 1.3628.0 with applicationLogs query filter / follow options

- charts/gitops-runtime/values.yaml
fix: allow concurrent reading of git repo file content ([#6473](https://github.com/codefresh-io/argo-platform/issues/6473))
[CR-29706](https://codefresh-io.atlassian.net/browse/CR-29706)
[ADR](https://codefresh-io.atlassian.net/wiki/spaces/RND/pages/3627515929/ADR+6+issues+when+promoting+between+multiple+repositories)
[CR-29706]: https://codefresh-io.atlassian.net/browse/CR-29706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update app-proxy image tags to 1.3642.0

- charts/gitops-runtime/templates/eventbus/codefresh-eventbus.yaml
- charts/gitops-runtime/tests/eventbus_test.yaml
- charts/gitops-runtime/values.yaml
> feat: jetstream eventbus

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
…p proxy to 1.3636.0-fix-2-cr-30274-0.22.1-42ccdd3
> chore: upgrade gitops operator to 0.0.0-cr-29944-0.8.6-832833c and app proxy to 1.3636.0-fix-2-cr-30274-0.22.1-42ccdd3

- charts/gitops-runtime/values.yaml
> fix: update leader elector image tag to remove version prefix 'v'

- charts/gitops-runtime/values.yaml
> chore(CR-30337): updated codefresh-gitops-operator

- charts/gitops-runtime/tests/cf-argocd-extras_test.yaml
> fix: remove checksum tests as they fail when chart version changes

- charts/gitops-runtime/Chart.yaml
> chore: bumped argocd to 8.0.6-8-cap-v3.0.2-2025-08-12-9c8dfae9

- charts/gitops-runtime/values.yaml
fix: argo-cd logs call ([#6616](https://github.com/codefresh-io/argo-platform/pull/6616))
> fix(app-proxy): update cap-app-proxy image tags to 1.3718.0

- .github/workflows/component-test.yaml
> feat(component-tests): Trigger test run for release branches

- installer-image/Dockerfile
update cli-v2 in installer
fix token validation code
> update cli-v2 in installer - fix token validation code

- installer-image/Dockerfile
> chore(CR-30832): updated cli-v2, kubectl

- charts/gitops-runtime/values.yaml
> chore(CR-30901): updated cap-app-proxy with security fixes

- charts/gitops-runtime/Chart.yaml
> feat: OSS-522 cherry-pick sec advisory ghsa-786q-9hcg-v9ff

- .github/workflows/component-test.yaml
- charts/gitops-runtime/Chart.yaml
> Feat: OSS-522 cherry-pick sec advisory-ghsa-786q-9hcg-v9ff

- charts/gitops-runtime/values.yaml
(cherry picked from commit cfe5413f2a29663c3affc52f1a31aefe1d8a911d)
> (Chore-30966): update sealed secrets controller 

- charts/gitops-runtime/Chart.yaml
> chore(OSS-697): bump argo-rollouts

- .github/workflows/component-test.yaml
> chore: disable component tests

- README.md
- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> backport redis bump fix 0.24

- charts/gitops-runtime/templates/_helpers.tpl
> feat:added runtime label to codefresh-cm

- charts/gitops-runtime/templates/_components/gitops-operator/crds/promotiontasks.yaml
- charts/gitops-runtime/values.yaml
Updating the CRD to align with the operator updates: https://github.com/codefresh-io/codefresh-gitops-operator/pull/292
> feat: add runWorkflow step handler
