- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/templates/_components/_common_helpers.yaml
- charts/gitops-runtime/templates/_components/cap-app-proxy/environment-variables/_main-container.yaml
- charts/gitops-runtime/tests/app-proxy-misc_test.yaml
To allow passing env vars like
```
app-proxy:
env:
NODE_TLS_REJECT_UNAUTHORIZED: 0
```
> feat: update env-vars helper template

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
new app-proxy fixes the helm-to-gitops flow, and writes the correct repository string to the values file
> bumped app-proxy to `1.2593.0`

- charts/gitops-runtime/Chart.yaml
> CR-22268-argo-cd-vuln-fix-update

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
bump gitops-operator to `1.0.3`
fix env vars in template
> bump gitops-operator to `1.0.3`

- charts/gitops-runtime/Chart.yaml
bump gitops-operator to `1.0.4`
removes productSelector and priority fields
> bump gitops-operator to `1.0.4`

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
> Release 0.5.0

- charts/gitops-runtime/Chart.yaml
jsonPath to application versions uses format with $ sign for root element
Align with promotion
> update argo-cd to 5.53.12-7-cap-2.9-2024.3.12-b23aa3fb6

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/templates/codefresh-cm.yaml
- charts/gitops-runtime/values.yaml
added `runtime.isConfigurationRuntime` field, which will end up in the `codefresh-cm` ConfigMap
will be used by app-proxy when setting up the isc. if set to `true` - the `in-cluster` app will include the `resources/configurations/**/*.yaml` path as well.
> feat: added isConfigurationRuntime field

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
fix notification configuration overrides
allow end users to define their own `argo-cd.notifications` fields, without it messing with configurations we need for the promotion flows
> updated argo-cd helm chart to `6.7.18-1-cap-2.10-2024.3.29-1dcc54e29`

- charts/gitops-runtime/Chart.yaml
> Updated gitops-operator chart to 1.0.16

- charts/gitops-runtime/Chart.yaml
bump codefresh-gitops-operator chart to 1.0.17 to allow missing promotion flow label
> feat: updated codefresh-gitops-operator chart to 1.0.17

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/ci/values-all-images.yaml
- charts/gitops-runtime/tests/values/mandatory-values-ingress.yaml
- charts/gitops-runtime/tests/values/mandatory-values-no-token.yaml
- charts/gitops-runtime/tests/values/mandatory-values.yaml
- charts/gitops-runtime/values.yaml
- installer-image/Dockerfile
- scripts/private-registry-utils/Dockerfile
* updated codefresh-gitops-operator chart to 1.0.17
* BREAKING CHANGE: no longer checking commit message for `[promotion:<flow>]` in operator side. making the check according to Product definition in the platform side
* added argocd-notifications-controller as sidecar in gitops-operator pod
* allow empty Release label on promotion-wrapper Workflow
* updated cap-app-proxy to 1.2835.0
* Add garage for workflow artifacts and logs (disabled by default)
* support multi-arch in tunnel-client
> Release-0.7.1

- charts/gitops-runtime/values.yaml
removed values from argocd-notifications-cm (they have already moved to gitops-operator-notifications-cm)
> Remove old notifications values

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/values.yaml
promotion-wrapper workflow now handles no-change promotions as non-failures, and continue the release
> Updated gitops-operator chart to 1.0.19

- charts/gitops-runtime/Chart.yaml
> security - update tunnel client image to new alpine

- charts/gitops-runtime/Chart.yaml
> upgrade codefresh-gitops-operator to 1.0.23

- charts/gitops-runtime/Chart.yaml
https://codefresh-io.atlassian.net/browse/CR-23749
> feat: update argo-cd with v2 event-reporter support of CA cert

- charts/gitops-runtime/Chart.yaml
> fix: argo-cd with reporting application event from queue instead of requesting live state

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> feat: Gitops operator upgrade

- charts/gitops-runtime/Chart.yaml
> fix - ArgoCD event reporter servicemonitor selector labels

- charts/gitops-runtime/Chart.yaml
this same changes as in https://github.com/codefresh-io/gitops-runtime-helm/pull/238/files
but according to new release flow
> feat: gitops-operator update with critical and high vuln fixes

- charts/gitops-runtime/Chart.yaml
update argo-workflows chart to 0.41.11-v3.5.8-cap-CR-22608
syncing with argo-workflows upstream, fixing sec-vulns
> Feat: update argo-workflows chart to 0.41.11-v3.5.8-cap-CR-22608

- charts/gitops-runtime/Chart.yaml
update argo-workflows chart to 0.41.11-v3.5.8-cap-CR-22608 (2nd attempt)
syncing with argo-workflows upstream, fixing sec-vulns
> Feat: update argo-workflows chart to 0.41.11-v3.5.8-cap-CR-22608 (2nd attempt)

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/ci/default-values-custom-tls.yaml
- charts/gitops-runtime/templates/gitops-operator.yaml
- charts/gitops-runtime/tests/custom-ca_test.yaml
> feat: gitops operator custom CA certificates injection

- charts/gitops-runtime/Chart.yaml
> patch: gitops operator - improve error handling and prevent changes to promotions notifications configuration

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
updated app-proxy image to 1.2962.0
updated gitops-operator helm chart to 0.2.5
gitops-operator will get commitInfo data when creating a promotion-workflow for a manual trigger made by the user.
this will require the platform to run api-graphql >=1.2962.0
> feat: add commit info in tasks

- charts/gitops-runtime/Chart.yaml
update argo-workflows to v3.5.9
fixes sec vulns
> chore: update argo-workflows chart to `0.41.12-v3.5.9-cap-CR-24929`

- charts/gitops-runtime/Chart.yaml
fix: update codefresh-gitops-operator to `0.2.9`
fixed promotion trigger from argo-cd notifications
> fix: update codefresh-gitops-operator to `0.2.9`

- charts/gitops-runtime/values.yaml
update app-proxy to `1.2987.1`
adds support for new drag-n-drop query, that operates the same way as other promotion flows (manual trigger or git trigger)
> feat: update app-proxy to `1.2987.1`

- charts/gitops-runtime/values.yaml
added default value of false
this value is already being used in pre-install hook. if set - will not attempt to make a web request to ingress host
> added default value and description for ingress `skipValidation`

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
> feat: update to upstream argo-cd 2.12.3 and helm 7.4.7

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
* bump gitops-operator to v0.2.13- support PR in promotion-wrapper and webhook
* bump cap-app-proxy to v1.3021.0 - expose mergedPullRequestBySha query
> feat: support PR in promotions

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
Updating codefresh-gitops-operator and cap-app-proxy to new versions.
The new version includes changes to help show the initiator of promotion product releases triggered from a git commit.
https://codefresh-io.atlassian.net/browse/CR-23402
Original PR 1: https://github.com/codefresh-io/gitops-runtime-helm/pull/303
Original PR 2: https://github.com/codefresh-io/gitops-runtime-helm/pull/304
argo-platform changes: https://github.com/codefresh-io/argo-platform/pull/5617
gitops-operator changes: https://github.com/codefresh-io/codefresh-gitops-operator/pull/87
> feat: Add Product Release Initiator functionality

- charts/gitops-runtime/templates/gitops-operator.yaml
when a customer sets argo-cd `fullnameOverride`, propagate the value into the gitops-operator subchart
> fix: inject the correct argo-cd server url into gitops-operator

- charts/gitops-runtime/Chart.yaml
fix memory leak in manager container
> chore: update codefresh-gitops-operator to 0.3.6

- charts/gitops-runtime/values.yaml
new app-proxy handles git operation in a much better way
the main problem was a promotion release trying to commit to multiple applications in the same runtime, in parallel. the new app-proxy handles it without a problem.
> chore: update cap-app-proxy to `1.3131.0` - improve locking around git operations

- charts/gitops-runtime/templates/_helpers.tpl
- charts/gitops-runtime/templates/gitops-operator.yaml
- charts/gitops-runtime/tests/gitops-controller-misc_test.yaml
use the defined argo-cd.configs.params['server.rootpath'] value when defining ARGO_CD_URL for gitops-operator
> fix: use the rootpath from argo-cd config.params values, when injecting ARGO_CD_URL to gitops-operator

- charts/gitops-runtime/Chart.yaml
allow override of promotion-wrapper workflowTemplate
> chore: update gitops-operator to 0.3.8 - support manual-sync applications

- charts/gitops-runtime/Chart.yaml
> chore: update gitops-operator to 0.3.8 - changed gitlog to take all commits since the last call

- charts/gitops-runtime/templates/_helpers.tpl
- charts/gitops-runtime/templates/gitops-operator.yaml
- charts/gitops-runtime/tests/gitops-controller-misc_test.yaml
gitops-operator should get ARGO_CD_URL without the protocol. the value ends up as an env variable to `argocd` binary, which fails if the protocol is supplied
> fix: don't use protocol for ARGO_CD_URL in gitops-operator

- charts/gitops-runtime/Chart.yaml
* fix: add retry in case workflow was not suspend yet (https://github.com/codefresh-io/codefresh-gitops-operator/pull/101)
* use argocd-get-global-tmpl on exit hook (https://github.com/codefresh-io/codefresh-gitops-operator/pull/103)
> feat: updated codefresh-gitops-operator to 0.3.10

- charts/gitops-runtime/Chart.yaml
update codefresh-gitops-operator to 0.3.11
support non-github promotions (commit only)
> feat: base git-providers support

- charts/gitops-runtime/values.yaml
> add req and lim for ephemeral storage (argo-workflows)

- charts/gitops-runtime/templates/_components/internal-router/_service.yaml
I have discovered a relatively easy way to run a gitops runtime in a local Kind cluster against a local (dev) instance of codefresh running in docker. The only thing missing from the existing helm chart is the ability to set the `nodePort` value on the `internal-router` service. Note: You can already set the service type to `NodePort` but you just can't specify the nodePort that it uses, which we need to for my setup.
There has been some instability with the use of vclusters and so we're trying to find a way to run a local dev setup against a local cluster with a runtime. I believe I have found a solution that works quite well.
Old PR: https://github.com/codefresh-io/gitops-runtime-helm/pull/347
> feat: Add ability to set nodePort on internal-router service

- charts/gitops-runtime/Chart.yaml
fix release retry in case it failed on workflow resume
> chore: update codefresh-gitops-operator to 0.3.13

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> chore: update argo-workflows to 0.45.1-v3.6.2-cap-CR-26293

- charts/gitops-runtime/Chart.yaml
> fix: update argo-cd to 2.12.3-2024.12.23-4a8e092c0-with-dex-and-redis-bump

- installer-image/Dockerfile
* update cli-v2 from 0.1.68 to 0.1.69
* update kubectl from 1.28.12 to 1.32.0
fixes crutical
[CVE-2024-45337](https://pkg.go.dev/vuln/GO-2024-3321)
fixes high:
[CVE-2024-45338](https://pkg.go.dev/vuln/GO-2024-3333), [CVE-2024-45338](https://pkg.go.dev/vuln/GO-2024-3333), [PRISMA-2022-0227](https://github.com/emicklei/go-restful/issues/497)
fixes medium:
[CVE-2024-53862](https://pkg.go.dev/vuln/GO-2024-3303)
> fix: update cli-v2 from 0.1.68 to 0.1.69

- charts/gitops-runtime/Chart.yaml
updated codefresh-gitops-operator to 0.3.19 [#111](https://github.com/codefresh-io/codefresh-gitops-operator/pull/111)
fixed security vulnerabilities
critical: [CVE-2024-45337](https://pkg.go.dev/vuln/GO-2024-3321)
high: [CVE-2024-5321](https://pkg.go.dev/vuln/GO-2024-2994), [CVE-2024-0793](https://pkg.go.dev/vuln/GO-2024-3277), [CVE-2024-40634](https://pkg.go.dev/vuln/GO-2024-3002)
medium: [CVE-2024-41666](https://pkg.go.dev/vuln/GO-2024-3006)
low: [CVE-2024-51744](https://pkg.go.dev/vuln/GO-2024-3250)
> fix: security-vulns in codefresh-gitops-operator

- charts/gitops-runtime/Chart.yaml
> feat: bump gitops operator with promotion hooks support

- charts/gitops-runtime/templates/hooks/pre-install/validate-values.yaml
> Fix(job): argument list too long

- charts/gitops-runtime/Chart.yaml
https://github.com/codefresh-io/argo-helm/pull/126
https://github.com/codefresh-io/argo-helm/releases/tag/argo-cd-7.7.14-3-cap-2.13.3-2025.2.12-7bfd6c858
> fix: bump argocd helm to argo-cd-7.7.14-3-cap-2.13.3-2025.2.12-7bfd6c858

- charts/gitops-runtime/Chart.yaml
> chore: updated gitops-operator version to 0.3.26

- charts/gitops-runtime/Chart.yaml
> chore(argo-workflows): bump argo-workflows to 0.45.2-v3.6.4-cap-CR-27392

- charts/gitops-runtime/Chart.yaml
* Argo Rollouts was updated from 1.7.1 to 1.7.2
* Extra security fixes were done (as reported by Prisma Cloud)
* To bring new features to customers
* To offer a secure distribution of Argo Rollouts 
See JIRA CR-26082
> feat: upgrade Argo Rollouts to 1.7.2 plus security fixes

- charts/gitops-runtime/Chart.yaml
- Increase the num of retries to wait for workflow to be suspended = 31 sec in total
- Avoid looking for suspended workflow if there are no matching wrappers
> chore: bump gitops-operator version to 0.3.27

- charts/gitops-runtime/Chart.yaml
bump gitops-operator to version 0.4.7
Related Issues:
- [CR-27686](https://codefresh-io.atlassian.net/browse/CR-27686)
- [CR-27071](https://codefresh-io.atlassian.net/browse/CR-27071)
[CR-27686]: https://codefresh-io.atlassian.net/browse/CR-27686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CR-27071]: https://codefresh-io.atlassian.net/browse/CR-27071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: bump gitops-operator to version 0.4.7

- charts/gitops-runtime/templates/gitops-operator.yaml
- charts/gitops-runtime/tests/gitops-operator_test.yaml
Set `LEADER_ELECT ` env var to `true` if gitops-operator has more than 1 replicas
> feat(gitops-operator): set LEADER_ELECT based on replicaCount

- scripts/verify-argocd-auto-detection.sh
> feat: add script to verify Argo CD service labels for auto-detection

- charts/gitops-runtime/Chart.yaml
Update cf-argocd-extras dependency in parent chart to incorporate the YAML parsing error handling improvements. This update improves the system's resilience when encountering malformed YAML files during resource manifest retrieval.
> chore(deps): update cf-argocd-extras dependency to 0.3.13

- charts/gitops-runtime/Chart.yaml
allow PromotionFlow with no steps
> chore(deps): update codefresh-gitops-operator version to 0.5.1

- charts/gitops-runtime/templates/_helpers.tpl
- charts/gitops-runtime/tests/cf-argocd-extras_test.yaml
- charts/gitops-runtime/tests/external_argocd_test.yaml
> fix: argocd fullname template; feat: add sources-server and event-reporter versions to codefresh-cm ConfigMap

- charts/gitops-runtime/Chart.yaml
gitops operator changes: https://github.com/codefresh-io/codefresh-gitops-operator/pull/136
> chore(deps): update codefresh-gitops-operator version to 0.5.2

- charts/gitops-runtime/templates/_helpers.tpl
- charts/gitops-runtime/templates/event-reporters/rollout-reporter/clusterrolebinding.yaml
- charts/gitops-runtime/templates/event-reporters/rollout-reporter/eventsource.yaml
- charts/gitops-runtime/templates/event-reporters/rollout-reporter/rbac.yaml
- charts/gitops-runtime/templates/event-reporters/rollout-reporter/sensor.yaml
- charts/gitops-runtime/templates/event-reporters/rollout-reporter/serviceaccount.yaml
- charts/gitops-runtime/tests/external_argo_rollouts_test.yaml
- charts/gitops-runtime/values.yaml
Allow to install rollout-reporter with external Argo Rollouts.
```yaml
global:
external-argo-rollouts:
rollout-reporter:
enabled: true
argo-rollouts:
enabled: false
```
> feat: rollout-reporter with external argo rollouts

- charts/gitops-runtime/Chart.yaml
Bumping gitops operator version to include this change: https://github.com/codefresh-io/codefresh-gitops-operator/pull/144
> chore: bump gitops operator version

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> chore(CR-28616): updated sealed-secrets

- charts/gitops-runtime/Chart.yaml
Extra security fixes were done (as reported by Prisma Cloud)
To offer a secure distribution of Argo Rollouts
See JIRA CR-28008
> feat: security fixes for Argo Rollouts 1.7.2

- charts/gitops-runtime/templates/hooks/pre-install/validate-values.yaml
- charts/gitops-runtime/values.yaml
- installer-image/Dockerfile
make sure argo-cd is >=2.12 and <3
> feat: add Argo CD version check and validation in pre-install hook

- charts/gitops-runtime/values.yaml
update app-proxy image tag to `1.3470.0`
fixes promotion process file version checks, and retry push after pull+merge in correct cases
> fix: update app-proxy image tag to 1.3470.0 - fix file revision validation

- charts/gitops-runtime/templates/hooks/pre-install/rbac.yaml
- charts/gitops-runtime/templates/hooks/pre-install/validate-usage.yaml
- charts/gitops-runtime/values.yaml
- installer-image/Dockerfile
A pre-install hook with the ability to be disabled
Prevents runtime installation if clusters limit is reached.
The final validation will take place during the runtime registration on the platform.
This hook allows us to stop the installation at an early stage.
It's not a reliable mechanism, just an additional one to save time and resources.
This PR was recreated with new branch name from this one:
https://github.com/codefresh-io/gitops-runtime-helm/pull/452
> feat: limits enforcement in runtime installation

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
Changes:
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/145
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/147
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/149
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/150
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/151
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/152
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/137
- https://github.com/codefresh-io/codefresh-gitops-operator/issues/153
> bump codefresh gitops operator version

- charts/gitops-runtime/Chart.yaml
> chore: update codefresh-gitops-operator version to 0.7.3 - fix missing argo-workflows permission

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/values.yaml
> feat(event-reporter): add pdb and serviceMonitor templates

- charts/gitops-runtime/templates/_components/cap-app-proxy/_deployment.yaml
- charts/gitops-runtime/templates/_components/cap-app-proxy/_service.yaml
- charts/gitops-runtime/templates/_components/cap-app-proxy/_servicemonitor.yaml
- charts/gitops-runtime/templates/app-proxy/servicemonitor.yaml
- charts/gitops-runtime/values.yaml
Add ServiceMonitor resource definition to enable monitoring of the app-proxy's http-metrics endpoint. This change allows for better observability and performance tracking of the service.
> chore(app-proxy): add ServiceMonitor configuration for metrics monitoring

- charts/gitops-runtime/README.md
- charts/gitops-runtime/README.md.gotmpl
- charts/gitops-runtime/values.yaml
> fix - remove archiveLogs=true as it breaks workflow execution with no configured artifact storage

- .gitignore
- charts/gitops-runtime/templates/event-reporter.yaml
- charts/gitops-runtime/tests/cf-argocd-extras_test.yaml
Event-reporter should use correct redis svc address when redis HA is enabled
```yaml
gitops-runtime:
global:
...
argo-cd:
redis-ha:
enabled: true
```
> fix: event-reporter invalid redis-ha url

- charts/gitops-runtime/Chart.yaml
> chore: bump gitops-operator v0.7.11

- charts/gitops-runtime/templates/hooks/pre-install/validate-values.yaml
no need for env variable - the `argocd-cmd-params-cm` ConfigMap name is hard-coded into argo-helm templates
the current check does not include the `ARGOCD_CM_PARAMS_NAME` env var at all, which makes the root.path check fail (with a warning) every time. will not work if customers do use a root.path value in their byo installtion.
> fix: update ConfigMap name in Argo CD root path retrieval script

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/templates/event-reporter.yaml
- charts/gitops-runtime/templates/sources-server.yaml
- charts/gitops-runtime/tests/cf-argocd-extras_test.yaml
Add support for custom platform TLS certificates in event-reporter and sources-server 
https://codefresh-io.atlassian.net/browse/CR-28947
> feat: add support for custom TLS certificates from the platform

- charts/gitops-runtime/Chart.yaml
bump argo cd to v2.14.9-2025-06-08-8821b48e bumped x/crypto to 0.35.0, bumped go to 1.23.0
https://github.com/codefresh-io/argo-helm/pull/175
bump redis to 7.4.4 dex to 2.43.1 redis-ha chart to 4.33.4
https://github.com/codefresh-io/argo-helm/pull/174
> feat: bumped argocd chart to 7.8.23-9-cap-v2.14.9-2025-06-08-8821b48e

- charts/gitops-runtime/Chart.yaml
fix embedded promotion-wrapper-workflow merge-args step
previous chart included the wrong `/jq` command in the step. should be `jq`
> chore: bump codefresh-gitops-operator version to 0.7.20

- charts/gitops-runtime/values.yaml
new app-proxy correctly pull-merges when needed
previous app-proxy switch from isomorphic-git to simple-git had an wrong check for when to perform a pull-merge when push failed.
> chore: update app-proxy image tags to 1.3600.0 - fix check for pull-merge

- charts/gitops-runtime/Chart.yaml
bump codefresh-gitops-operator version to 0.7.22
security vulnerability fix
> chore: bump codefresh-gitops-operator version to 0.7.22

- charts/gitops-runtime/Chart.yaml
> chore: bump codefresh-gitops-operator version to 0.7.25

- charts/gitops-runtime/templates/_components/cap-app-proxy/environment-variables/_main-container.yaml
- charts/gitops-runtime/templates/app-proxy/_app-proxy-env.yaml
app-proxy will send current env vars to simple-git execution
added GIT_SSAL_CAINFO to let git binary access self-signed servers
on-prem git servers with self-signed certificates would fail cloning.
> chore: removed unused env var in app-proxy

- charts/gitops-runtime/Chart.yaml
https://github.com/codefresh-io/codefresh-gitops-operator/pull/208
> fix: Update gitops operator subchart to 0.8.0

- charts/gitops-runtime/Chart.yaml
This reverts commit https://github.com/codefresh-io/codefresh-gitops-operator/commit/979dad5d42d0f466514bc0aa68605d3726cae37e.
The impl was getting product on the cluster, which will not be exist on runtime that are not configuration runtimes
> chore: bump gitops operator to revert relative path

- charts/gitops-runtime/Chart.yaml
This reverts commit https://github.com/codefresh-io/codefresh-gitops-operator/commit/979dad5d42d0f466514bc0aa68605d3726cae37e.
The impl was getting product on the cluster, which will not be exist on runtime that are not configuration runtimes
> chore: bump gitops operator

- charts/gitops-runtime/Chart.yaml
stop attempting to resume a non-running workflow
without that change, the gitops-operator might go into a long-running loop of attempting to resume a terminated workflow, until it will be garbage-collected by the cluster (defaults to 2h). this will also block any other application reconciliation during that time.
> chore: update codefresh-gitops-operator version to 0.8.4

- charts/gitops-runtime/Chart.yaml
Gitops Operator change: https://github.com/codefresh-io/codefresh-gitops-operator/pull/216
We are updating the look-back time period to 2 hours to make the operator work better specifically for Spare in the short term. We have another ticket (https://codefresh-io.atlassian.net/browse/CR-29944) to fix this area of the code so that resume workflows will work no matter how long ago a commit was made.
> chore: update gitops operator to 0.8.5

- charts/gitops-runtime/values.yaml
* fix(dependencies): update cf-git-providers to version ^0.15.2 ([#6528](https://github.com/codefresh-io/argo-platform/pull/6528))
* fix: unhandledRejection when getting rate-limit error on github api calls ([#6528](https://github.com/codefresh-io/argo-platform/pull/6528))
[CR-30068](https://codefresh-io.atlassian.net/browse/CR-30068)
[CR-30068]: https://codefresh-io.atlassian.net/browse/CR-30068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: update app-proxy image tags to 1.3651.0

- charts/gitops-runtime/templates/_components/event-reporters/_helpers.tpl
- charts/gitops-runtime/templates/_components/event-reporters/rollout-reporter/_sensor.yaml
- charts/gitops-runtime/templates/_components/event-reporters/workflow-reporter/_sensor.yaml
- charts/gitops-runtime/templates/eventbus/codefresh-eventbus.yaml
- charts/gitops-runtime/tests/event-reporters-sensors_test.yaml
- charts/gitops-runtime/tests/eventbus_test.yaml
- charts/gitops-runtime/values.yaml
* feat: jetstream eventbus
enable the option to switch between nats and jetstream eventbus types
seems like nats is very unstable. switching to jetstream should hopefully fix that
> feat: jetstream eventbus (#589)

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
- charts/gitops-runtime/templates/_components/internal-router/_deployment.yaml
- charts/gitops-runtime/values.yaml
https://github.com/codefresh-io/argo-helm/pull/184
https://github.com/codefresh-io/argo-cd/pull/417
Security vulns
> feat: updated argo cd to 8.0.6-5-cap-v3.0.2-2025-07-21-ac26d0e2 with helm and go-git bump

- charts/gitops-runtime/templates/_components/gitops-operator/_env.yaml
fix: GITOPS_OPERATOR_VERSION should be based upon its own tag, and not the chart appVersion
the version check in the platform expects to check the gitops-operator image tag, and not the chart version
> fix: GITOPS_OPERATOR_VERSION should be based upon its own tag, and not the chart appVersion

- charts/gitops-runtime/values.yaml
fix: return the pushed commit sha [#6560](https://github.com/codefresh-io/argo-platform/pull/6560)
> chore: update cap-app-proxy image tags to 1.3680.0

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/README.md
https://github.com/codefresh-io/argo-helm/pull/186
https://github.com/codefresh-io/argo-helm/pull/185
> fix: argo helm bump redis version

- charts/gitops-runtime/templates/_helpers.tpl
without the quote, using `*.some.domain` in `global.noProxy` would mess up all the env variables of the app-proxy.
> quote proxy env vars

- charts/gitops-runtime/Chart.yaml
Argo CD v3 [shows as out-of-sync any CRDs](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.14-3.0/#removing-default-ignores-of-preserveunknownfields-for-crd) that have preserveUnknownFields: false
> feat: solve out-of-sync crds in Argo CD v3

- charts/gitops-runtime/values.yaml
> fix: Updated gitops operator not to requeue on known release creation failures

- charts/gitops-runtime/values.yaml
fix: remote-cluster application fails to sync due to its project ([#6639](https://github.com/codefresh-io/argo-platform/pull/6639))
> chore(app-proxy): update cap-app-proxy image tags to 1.3727.0

- charts/gitops-runtime/templates/hooks/pre-uninstall/cleanup-resources.yaml
- charts/gitops-runtime/templates/hooks/pre-uninstall/delete-runtime-from-platform.yaml
- charts/gitops-runtime/templates/hooks/pre-uninstall/rbac.yaml
re-open of #642
This pull request makes a minor update to the `cleanup-resources.yaml` hook template by changing the `serviceAccount` used for the cleanup job. The new service account, `runtime-cleanup`, is likely more appropriate for the job's permissions and responsibilities.
- Changed the `serviceAccount` in the `charts/gitops-runtime/templates/hooks/pre-uninstall/cleanup-resources.yaml` file from `argocd-application-controller` to `runtime-cleanup` to better align with the job's purpose.
```
Error creating: pods "cleanup-runtime-resources-" is forbidden: error looking up service account codefresh-gitops/argocd-application-controller: serviceaccount "argocd-application-controller" not found 
```
> `codefresh-gitops` mentioned in the error message above refers to a namespace.
Use case: …
> fix: service account for cleanup runtime resources

- charts/gitops-runtime/templates/_components/gitops-operator/crds/promotiontasks.yaml
- charts/gitops-runtime/values.yaml
Apply changes required for operator update. Operator PR: https://github.com/codefresh-io/codefresh-gitops-operator/pull/278
> feat: add error messages for appStatus

- charts/gitops-runtime/Chart.yaml
- charts/gitops-runtime/templates/_helpers.tpl
- tests/component-tests/setup/values/gitea.values.yaml
- tests/component-tests/startup.yaml
> feat: added runtime label to codefresh cm

- charts/gitops-runtime/templates/_components/gitops-operator/crds/promotiontasks.yaml
- charts/gitops-runtime/values.yaml
Related Operator PR: https://github.com/codefresh-io/codefresh-gitops-operator/pull/287
> fix: promotion values can't be empty

- charts/gitops-runtime/templates/_components/gitops-operator/crds/promotiontasks.yaml
- charts/gitops-runtime/values.yaml
Based on changes from https://github.com/codefresh-io/codefresh-gitops-operator/pull/290
> feat: get commit author avatar url on getPromotionValues step
